# This workflows will build the docker image when a release is created
{% raw %}
name: Build and Push to GCP Artifact Registry

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: 'actions/checkout@v4'

          - name: Google authentication
            id: auth
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

          - name: Set up Google Cloud SDK
            uses: 'google-github-actions/setup-gcloud@v2'

          - name: Use gcloud CLI
            run: 'gcloud info'

          - name: Create repository
            run: |-
              gcloud artifacts repositories create ${{ secrets.GAR_REPO_NAME }} --repository-format=docker \
              --location=${{ secrets.GCP_REGION }} --description="Docker repository for {{cookiecutter.project_slug}}" \
              --project=${{ secrets.GCP_PROJECT_ID }}

          - name: gCloud docker auth
            run: |-
              gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

          - name: Build image
            run: docker build . --file Dockerfile --tag ${{ secrets.GAR_REPO_NAME }} --platform linux/amd64
            working-directory: .

          - name: Push image to GCP Artifact Registry
            run: docker push ${{ secrets.GAR_REPO_NAME }}
{% endraw %}