on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master
{% raw %}
name: macOS build
jobs:
    test-macOS:
        name: Build for Windows (${{ matrix.python-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
{% endraw %}
        strategy:
            fail-fast: false
            matrix:
              os: ["macOS-latest"]
              python-version: ["{{cookiecutter.python_version}}"]
{% raw %}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version}}

          - name: Install Poetry
            run: |
              pip install poetry

          - name: Configure Poetry
            run: |
              poetry config virtualenvs.create false

          - name: Install dependencies
            run: poetry install
            shell: bash
{% endraw %}